import re

# --- 1. CODE EXTRACTOR ---
def extract_code(llm_response: str) -> str:
    """
    Use Regex to strip conversational filler from LLM responses.
    Ensures only valid Python code is returned.
    """
    pattern = r"```python\n(.*?)```"
    match = re.search(pattern, llm_response, re.DOTALL)
    if match:
        return match.group(1).strip()
    # Fallback: If no markdown tags found, return stripped text
    return llm_response.strip()

# --- 2. REPORT GENERATOR ---
def generate_markdown_report(history):
    """
    Compiles the 'White Box' analysis from the session history
    into a clean Markdown document for export.
    """
    report = "# 🛠️ Engineering Refactor Report\n\n"
    
    report += "**Status:** Production Ready\n"
    report += "**Methodology:** White Box Analysis\n\n"
    
    for i, msg in enumerate(history):
        if msg['role'] == 'assistant':
            # Retrieve the rich summary generated by Node 4
            rich_summary = msg.get('summary', 'Analysis pending...')
            
            report += f"## Module Interaction {i//2 + 1}\n"
            report += f"{rich_summary}\n\n"
            report += "---\n"
            
    return report